global:
  scrape_interval: 15s
  - job_name: 'backend'
  metrics_path: '/'
  static_configs:
    - targets: ['backend:8000']


scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

